version: "3"
services:
  app:
    container_name: mogyuchi.com
    build: .
    tty: true
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
volumes:
  node_modules: {}