version: "3"
services:
  app:
    container_name: mogyuchi.com
    build: .
    tty: true
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: .
        target: /home/node/app
      - type: volume
        source: node_modules
        target: /home/node/app/node_modules
volumes:
  node_modules: {}
